version: '3'

services:
    nginx:
        build: 
            context: .
            dockerfile: nginx.Dockerfile
        image: django-app-nginx
        ports:
            - 80:80
        # depends_on:
        #     - website

    # website:
    #     build: .
    #     command: gunicorn photo_website.wsgi:application --bind 0.0.0.0:8000
    #     # volumes:
    #     #     - static_volume:/photo-portfolio/staticfiles
    #     #     - media_volume:/photo-portfolio/mediafiles
    #     expose:
    #       - 8000
