version: '3'

services:
    nginx:
        build: 
            context: .
            dockerfile: nginx.Dockerfile
        image: django-app-nginx
        ports:
            - 80:80
        depends_on:
            - webapp

    webapp:
        build:
            context: .
            dockerfile: app.Dockerfile
        image: django-app-web
        expose:
          - 8000
